[package]
name = "decipede"
version = "0.1.0"
authors = ["William Tange <will@tan.ge>"]
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
dioxus = { version = "0.4" }
dioxus-logger = "0.4.1"
dioxus-router = { version = "0.4", features = ["web"] }
dioxus-web = { version = "0.4" }
gloo-utils = "0.2.0"
log = "0.4.19"
mullvm-parser = { path = "../../llvm--/mullvm-parser" }
serde = "1.0.196"
wasm-bindgen = "0.2.91"
